### ISSUE TITLE
2장 39페이지 안되시는 분들

### ISSUE THREAD

**Issue by yunbinni** [madvirus/spring5fs#4]
책에서 gradle을 최신 버전으로 다운로드하라고 했지만
저는 오류가 났습니다.

[오류메시지 중 일부]
`Could not find method compile() for arguments [org.springframework:spring-context:5.0.2.RELEASE] on object of type`

그래서 gradle을 다시 4.4로 맞춰 설치해봤더니 잘되네요.
만약 안되셔서 찾아오신 분들을 위해 글 남깁니다.

**Comment by madvirus** [comment]
@yunbinni 책을 쓰는 시점의 최신 버전이었는데 버전을 명시적으로 안내해야 겠네요.
